import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
} from "docx";
import type { AnalysisResult } from "@/lib/types";

function safeFileName(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 70);
}

function createParagraph(text: string): Paragraph {
  return new Paragraph({
    children: [
      new TextRun({
        text,
        size: 22,
      }),
    ],
    spacing: {
      after: 160,
    },
  });
}

function createHeading(text: string, level: typeof HeadingLevel.HEADING_1 | typeof HeadingLevel.HEADING_2): Paragraph {
  return new Paragraph({
    text,
    heading: level,
    spacing: {
      before: 220,
      after: 120,
    },
  });
}

function createBullet(text: string): Paragraph {
  return new Paragraph({
    children: [
      new TextRun({
        text: `• ${text}`,
        size: 22,
      }),
    ],
    spacing: {
      after: 100,
    },
  });
}

function createSmallMuted(text: string): Paragraph {
  return new Paragraph({
    children: [
      new TextRun({
        text,
        size: 18,
        italics: true,
      }),
    ],
    spacing: {
      after: 160,
    },
  });
}

async function downloadDocx(doc: Document, fileName: string) {
  const blob = await Packer.toBlob(doc);
  const url = URL.createObjectURL(blob);

  const link = document.createElement("a");
  link.href = url;
  link.download = fileName;
  document.body.appendChild(link);
  link.click();
  link.remove();

  URL.revokeObjectURL(url);
}

export async function downloadCvDocx(result: AnalysisResult) {
  const fileName = `${safeFileName(result.jobTitle)}-${safeFileName(
    result.company
  )}-cv.docx`;

  const children: Paragraph[] = [
    new Paragraph({
      children: [
        new TextRun({
          text: result.jobTitle,
          bold: true,
          size: 32,
        }),
      ],
      alignment: AlignmentType.CENTER,
      spacing: {
        after: 80,
      },
    }),
    new Paragraph({
      children: [
        new TextRun({
          text: result.company,
          size: 22,
        }),
      ],
      alignment: AlignmentType.CENTER,
      spacing: {
        after: 240,
      },
    }),

    createHeading("Profile", HeadingLevel.HEADING_1),
    createParagraph(result.cv.profile),

    createHeading("Key Skills", HeadingLevel.HEADING_1),
    createParagraph(result.cv.keySkills.join(" | ")),

    createHeading("Professional Experience", HeadingLevel.HEADING_1),
    ...result.cv.experienceSections.flatMap((section) => [
      createHeading(section.role, HeadingLevel.HEADING_2),
      ...section.bullets.map((bullet) => createBullet(bullet)),
    ]),

    createHeading("ATS Keywords", HeadingLevel.HEADING_1),
    createParagraph(result.cv.atsKeywords.join(" | ")),

    createHeading("Tailoring Notes", HeadingLevel.HEADING_1),
    ...result.cv.changeNotes.map((note) => createBullet(note)),

    createSmallMuted(
      "Generated by the Job Application Helper prototype. Review and edit before submitting."
    ),
  ];

  const doc = new Document({
    sections: [
      {
        properties: {},
        children,
      },
    ],
  });

  await downloadDocx(doc, fileName);
}

export async function downloadCoverLetterDocx(
  result: AnalysisResult,
  version: "full" | "short"
) {
  const label = version === "full" ? "full-cover-letter" : "short-cover-letter";
  const fileName = `${safeFileName(result.jobTitle)}-${safeFileName(
    result.company
  )}-${label}.docx`;

  const letter =
    version === "full" ? result.coverLetter.full : result.coverLetter.short;

  const children: Paragraph[] = [
    new Paragraph({
        children: [
        new TextRun({
            text: result.candidateName || "Candidate Name",
            bold: true,
            size: 34,
        }),
        ],
        alignment: AlignmentType.CENTER,
        spacing: {
        after: 80,
        },
    }),
    new Paragraph({
        children: [
        new TextRun({
            text: `${result.jobTitle} · ${result.company}`,
            size: 22,
        }),
        ],
        alignment: AlignmentType.CENTER,
        spacing: {
        after: 240,
        },
    }),

    createHeading("Profile", HeadingLevel.HEADING_1),
    createParagraph(result.cv.profile),

    createHeading("Key Skills", HeadingLevel.HEADING_1),
    createParagraph(
        Array.from(new Set([...result.cv.keySkills, ...result.cv.atsKeywords]))
        .slice(0, 18)
        .join(" | ")
    ),

    createHeading("Professional Experience", HeadingLevel.HEADING_1),
    ...result.cv.experienceSections.flatMap((section) => [
        createHeading(section.role, HeadingLevel.HEADING_2),
        ...section.bullets.map((bullet) => createBullet(bullet)),
    ]),

    createSmallMuted(
        "Generated by the Job Application Helper prototype. Review and edit before submitting."
    ),
    ];

  const doc = new Document({
    sections: [
      {
        properties: {},
        children,
      },
    ],
  });

  await downloadDocx(doc, fileName);
}